### ISSUE TITLE
Feature Request: Synchronous version

### ISSUE THREAD

**Issue by agyemanjp** [pladaria/xml-reader#5]
can we have a synchronous version of this package?

**Comment by pladaria** [comment]
Hi,

It is already synchronous. The api is event-driven but event listeners are executed synchronously (eventemitter3 is used under the hood) so this code will print the `console.log` statements in order:

``` javascript
const Reader = require('xml-reader');

const parseXml = (xml) => {
    const reader = Reader.create({doneEvent: 'parse:done'});
    let result;
    reader.on('parse:done', data => {result = data});
    reader.parse(xml);
    return result;
};

const xml = '<root><item v=1/></root>';

console.log('1');
console.log(parseXml(xml));
console.log('2');
```

Of course this is only valid when you have the full XML, not for stream mode or chunked parsing.

Anyway, I will consider adding a parseSync method to the lib.

**Comment by pladaria** [comment]
I've published v.1.1.1 which includes a parseSync method.

From the README file:

``` javascript
const XmlReader = require('xml-reader');

const xml = '<doc>Hello!</doc>';

const result = XmlReader.parseSync(xml);
```

Please, check the [xml-query](https://github.com/pladaria/xml-query) package. It is very useful to read values from xml-reader results.
