### ISSUE TITLE
Add an option to exclude the parent key from AST

### ISSUE THREAD

**Issue by agyemanjp** [pladaria/xml-reader#6]
Please add an option to exclude the parent key from the AST. As it is now, the AST cannot be stringified because it will introduce infinite recursion.

Try this example code:

```
const xmlReader = require('xml-reader');
const markup = `<StackPanelVertical><Banner title="title" logo="logo.jpg"/><Footer/></StackPanelVertical>`;
const result = xmlReader.parseSync(markup);
console.log(JSON.stringify(result));
```

This will give an error. In most cases, there is no need for the parent key

**Comment by pladaria** [comment]
Thanks for the feedback, I'm going to add this option.
Meanwhile, as workaround, you can use `inspect` from the `util` module

``` javascript
 console.log(require('util').inspect(ast));
```

**Comment by pladaria** [comment]
I've published v.2.0.0 with an option to disable parent nodes. See README for details.

Thanks again for your feedback :)
