### ISSUE TITLE
Handle NameSpaces (Feature request)

### ISSUE THREAD

**Issue by tommrr** [pladaria/xml-reader#8]
Hi There,

Im interested in using your library for one of my projects, It involves parsing some XML with namespaces that change independently between files, is there away you could make the tag matching less strict.

XML:
```
  </ns0:head>
  <ns0:body style="s0" ns3:textAlign="center">
    <ns0:div>
```

Example JS
`reader.on('tag:*:div', (data) => console.log(data));`
rather than having to detail the exact namespace for the div as this may change between files.
`reader.on('tag:ns0:div', (data) => console.log(data));`

**Comment by pladaria** [comment]
Hi, 

You can listen to all tags and then filter:

```javascript
reader.on('tag', (name, data) => {
    if (name.startsWith('foo:') {
        console.log(`received a ${name} tag:`, data));
    }
};
```
